mutation AddCourse ($name: String!, $description: String, $defaultCredits: String, $courseCode: String!, $termsOffered: String) {
  createCourse (
    name: $name,
    description: $description,
    defaultCredits: $defaultCredits,
    courseCode: $courseCode,
    termsOffered: $termsOffered
  ) {
      id
  }
}